# -*- cmake -*-
include(Linking)
include(Prebuilt)

set(CARES_FIND_QUIETLY ON)
set(CARES_FIND_REQUIRED ON)

if (STANDALONE)
  include(FindCARes)
elseif (TARGET c-ares::cares)
  if (WINDOWS)
    add_definitions("-DCARES_STATICLIB")
  endif (WINDOWS)
  set(CARES_LIBRARIES c-ares::cares)
  get_target_property(_cares_incs c-ares::cares INTERFACE_INCLUDE_DIRECTORIES)
  if (_cares_incs)
    set(CARES_INCLUDE_DIRS "${_cares_incs}")
  else ()
    set(CARES_INCLUDE_DIRS "")
  endif ()
elseif (TARGET cares)
  if (WINDOWS)
    add_definitions("-DCARES_STATICLIB")
  endif (WINDOWS)
  set(CARES_LIBRARIES cares)
  get_target_property(_cares_incs cares INTERFACE_INCLUDE_DIRECTORIES)
  if (_cares_incs)
    set(CARES_INCLUDE_DIRS "${_cares_incs}")
  else ()
    set(CARES_INCLUDE_DIRS "")
  endif ()
else ()
  use_prebuilt_binary(ares)
  if (WINDOWS)
    add_definitions("-DCARES_STATICLIB")
    set(CARES_LIBRARIES areslib)
  endif (WINDOWS)
  set(CARES_INCLUDE_DIRS ${LIBS_PREBUILT_DIR}/include/ares)
endif ()
