/** 
 *
 * Copyright (c) 2009-2011, Kitty Barnett
 * 
 * The source code in this file is provided to you under the terms of the 
 * GNU Lesser General Public License, version 2.1, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. Terms of the LGPL can be found in doc/LGPL-licence.txt
 * in this distribution, or online at http://www.gnu.org/licenses/lgpl-2.1.txt
 * 
 * By copying, modifying or distributing this software, you acknowledge that
 * you have read and understood your obligations described above, and agree to 
 * abide by those obligations.
 * 
 */
#ifndef RLV_DEFINES_H
#define RLV_DEFINES_H
#define RLV_EXTENSION_CMD_GETSETDEBUG_EX
#define RLV_EXTENSION_CMD_FINDFOLDERS
#define RLV_EXTENSION_FORCEWEAR_GESTURES
#define RLV_EXTENSION_STARTLOCATION
#define RLV_EXPERIMENTAL
#define RLV_EXPERIMENTAL_CMDS
#ifdef RLV_EXPERIMENTAL
	#define RLV_EXTENSION_FORCEWEAR_FOLDERLINKS
	#if LL_RELEASE_WITH_DEBUG_INFO || LL_DEBUG
	#endif
#endif
#ifdef RLV_EXPERIMENTAL_CMDS
	#define RLV_EXTENSION_CMD_ALLOWIDLE
	#define RLV_EXTENSION_CMD_GETCOMMAND
	#define RLV_EXTENSION_CMD_GETXXXNAMES
	#define RLV_EXTENSION_CMD_INTERACT
	#define RLV_EXTENSION_CMD_TOUCHXXX
#endif
const S32 RLV_VERSION_MAJOR = 2;
const S32 RLV_VERSION_MINOR = 9;
const S32 RLV_VERSION_PATCH = 0;
const S32 RLV_VERSION_BUILD = 0;
const S32 RLVa_VERSION_MAJOR = 2;
const S32 RLVa_VERSION_MINOR = 1;
const S32 RLVa_VERSION_PATCH = 0;
const S32 RLVa_VERSION_BUILD = 0;
#define RLV_WARNS		LL_WARNS("RLV")
#define RLV_INFOS		LL_INFOS("RLV")
#define RLV_DEBUGS		LL_DEBUGS("RLV")
#define RLV_ENDL		LL_ENDL
#define RLV_VERIFY(f)	if (!(f)) { RlvUtil::notifyFailedAssertion(#f, __FILE__, __LINE__); }
#if LL_RELEASE_WITH_DEBUG_INFO || LL_DEBUG
	#define RLV_DEBUG
	#define RLV_ERRS				LL_ERRS("RLV")
	#define RLV_ASSERT(f)			if (!(f)) { RLV_ERRS << "ASSERT (" << #f << ")" << RLV_ENDL; }
	#define RLV_ASSERT_DBG(f)		RLV_ASSERT(f)
#else
	#define RLV_ERRS				LL_WARNS("RLV")
	#ifndef RLV_RELEASE
		#define RLV_ASSERT(f)		RLV_VERIFY(f)
		#define RLV_ASSERT_DBG(f)
	#else
		#define RLV_ASSERT(f)
		#define RLV_ASSERT_DBG(f)
	#endif
#endif
#define RLV_ROOT_FOLDER					"#RLV"
#define RLV_CMD_PREFIX					'@'
#define RLV_PUTINV_PREFIX				"#RLV/~"
#define RLV_PUTINV_SEPARATOR				"/"
#define RLV_PUTINV_MAXDEPTH				4
#define RLV_SETROT_OFFSET				F_PI_BY_TWO
#define RLV_STRINGS_FILE				"rlva_strings.xml"
#define RLV_FOLDER_FLAG_NOSTRIP			"nostrip"
#define RLV_FOLDER_PREFIX_HIDDEN		'.'
#define RLV_FOLDER_PREFIX_PUTINV    	'~'
enum ERlvBehaviour {
	RLV_BHVR_DETACH = 0,
	RLV_BHVR_ATTACH,
	RLV_BHVR_ADDATTACH,
	RLV_BHVR_REMATTACH,
	RLV_BHVR_ADDOUTFIT,
	RLV_BHVR_REMOUTFIT,
	RLV_BHVR_SHAREDWEAR,
	RLV_BHVR_SHAREDUNWEAR,
	RLV_BHVR_UNSHAREDWEAR,
	RLV_BHVR_UNSHAREDUNWEAR,
	RLV_BHVR_EMOTE,
	RLV_BHVR_SENDCHAT,
	RLV_BHVR_RECVCHAT,
	RLV_BHVR_RECVCHATFROM,
	RLV_BHVR_RECVEMOTE,
	RLV_BHVR_RECVEMOTEFROM,
	RLV_BHVR_REDIRCHAT,
	RLV_BHVR_REDIREMOTE,
	RLV_BHVR_CHATWHISPER,
	RLV_BHVR_CHATNORMAL,
	RLV_BHVR_CHATSHOUT,
	RLV_BHVR_SENDCHANNEL,
	RLV_BHVR_SENDIM,
	RLV_BHVR_SENDIMTO,
	RLV_BHVR_RECVIM,
	RLV_BHVR_RECVIMFROM,
	RLV_BHVR_STARTIM,
	RLV_BHVR_STARTIMTO,
	RLV_BHVR_PERMISSIVE,
	RLV_BHVR_NOTIFY,
	RLV_BHVR_SHOWINV,
	RLV_BHVR_SHOWMINIMAP,
	RLV_BHVR_SHOWWORLDMAP,
	RLV_BHVR_SHOWLOC,
	RLV_BHVR_SHOWNAMES,
	RLV_BHVR_SHOWNAMETAGS,
	RLV_BHVR_SHOWHOVERTEXT,
	RLV_BHVR_SHOWHOVERTEXTHUD,
	RLV_BHVR_SHOWHOVERTEXTWORLD,
	RLV_BHVR_SHOWHOVERTEXTALL,
	RLV_BHVR_TPLM,
	RLV_BHVR_TPLOC,
	RLV_BHVR_TPLURE,
	RLV_BHVR_TPREQUEST,
	RLV_BHVR_VIEWNOTE,
	RLV_BHVR_VIEWSCRIPT,
	RLV_BHVR_VIEWTEXTURE,
	RLV_BHVR_ACCEPTPERMISSION,
	RLV_BHVR_ACCEPTTP,
	RLV_BHVR_ACCEPTTPREQUEST,
	RLV_BHVR_ALLOWIDLE,
	RLV_BHVR_EDIT,
	RLV_BHVR_EDITOBJ,
	RLV_BHVR_REZ,
	RLV_BHVR_FARTOUCH,
	RLV_BHVR_INTERACT,
	RLV_BHVR_TOUCHTHIS,
	RLV_BHVR_TOUCHATTACH,
	RLV_BHVR_TOUCHATTACHSELF,
	RLV_BHVR_TOUCHATTACHOTHER,
	RLV_BHVR_TOUCHHUD,
	RLV_BHVR_TOUCHWORLD,
	RLV_BHVR_TOUCHALL,
	RLV_BHVR_TOUCHME,
	RLV_BHVR_FLY,
	RLV_BHVR_SETGROUP,
	RLV_BHVR_UNSIT,
	RLV_BHVR_SIT,
	RLV_BHVR_SITTP,
	RLV_BHVR_STANDTP,
	RLV_BHVR_SETDEBUG,
	RLV_BHVR_SETENV,
	RLV_BHVR_ALWAYSRUN,
	RLV_BHVR_TEMPRUN,
	RLV_BHVR_DETACHME,
	RLV_BHVR_ATTACHOVER,
	RLV_BHVR_ATTACHTHIS,
	RLV_BHVR_ATTACHTHISOVER,
	RLV_BHVR_ATTACHTHISEXCEPT,
	RLV_BHVR_DETACHTHIS,
	RLV_BHVR_DETACHTHISEXCEPT,
	RLV_BHVR_ATTACHALL,
	RLV_BHVR_ATTACHALLOVER,
	RLV_BHVR_DETACHALL,
	RLV_BHVR_ATTACHALLTHIS,
	RLV_BHVR_ATTACHALLTHISEXCEPT,
	RLV_BHVR_ATTACHALLTHISOVER,
	RLV_BHVR_DETACHALLTHIS,
	RLV_BHVR_DETACHALLTHISEXCEPT,
	RLV_BHVR_ADJUSTHEIGHT,
	RLV_BHVR_CAMZOOMMAX,
	RLV_BHVR_CAMZOOMMIN,
	RLV_BHVR_CAMDISTMAX,
	RLV_BHVR_CAMDISTMIN,
	RLV_BHVR_CAMDRAWMAX,
	RLV_BHVR_CAMDRAWMIN,
	RLV_BHVR_CAMDRAWALPHAMAX,
	RLV_BHVR_CAMDRAWALPHAMIN,
	RLV_BHVR_CAMDRAWCOLOR,
	RLV_BHVR_CAMUNLOCK,
	RLV_BHVR_CAMAVDIST,
	RLV_BHVR_CAMTEXTURES,
	RLV_BHVR_TPTO,
	RLV_BHVR_VERSION,
	RLV_BHVR_VERSIONNEW,
	RLV_BHVR_VERSIONNUM,
	RLV_BHVR_GETATTACH,
	RLV_BHVR_GETATTACHNAMES,
	RLV_BHVR_GETADDATTACHNAMES,
	RLV_BHVR_GETREMATTACHNAMES,
	RLV_BHVR_GETOUTFIT,
	RLV_BHVR_GETOUTFITNAMES,
	RLV_BHVR_GETADDOUTFITNAMES,
	RLV_BHVR_GETREMOUTFITNAMES,
	RLV_BHVR_FINDFOLDER,
	RLV_BHVR_FINDFOLDERS,
	RLV_BHVR_GETPATH,
	RLV_BHVR_GETPATHNEW,
	RLV_BHVR_GETINV,
	RLV_BHVR_GETINVWORN,
	RLV_BHVR_GETGROUP,
	RLV_BHVR_GETSITID,
	RLV_BHVR_GETCOMMAND,
	RLV_BHVR_GETSTATUS,
	RLV_BHVR_GETSTATUSALL,
	RLV_BHVR_COUNT,
	RLV_BHVR_UNKNOWN
};
enum ERlvParamType {
	RLV_TYPE_UNKNOWN,
	RLV_TYPE_ADD,
	RLV_TYPE_REMOVE,
	RLV_TYPE_FORCE,
	RLV_TYPE_REPLY,
	RLV_TYPE_CLEAR
};
enum ERlvCmdRet {
	RLV_RET_UNKNOWN		= 0x0000,
	RLV_RET_RETAINED,
	RLV_RET_SUCCESS		= 0x0100,
	RLV_RET_SUCCESS_UNSET,
	RLV_RET_SUCCESS_DUPLICATE,
	RLV_RET_SUCCESS_DELAYED,
	RLV_RET_FAILED		= 0x0200,
	RLV_RET_FAILED_SYNTAX,
	RLV_RET_FAILED_OPTION,
	RLV_RET_FAILED_PARAM,
	RLV_RET_FAILED_LOCK,
	RLV_RET_FAILED_DISABLED,
	RLV_RET_FAILED_UNKNOWN,
	RLV_RET_FAILED_NOSHAREDROOT,
	RLV_RET_DEPRECATED
};
enum ERlvExceptionCheck
{
	RLV_CHECK_PERMISSIVE,
	RLV_CHECK_STRICT,
	RLV_CHECK_DEFAULT
};
enum ERlvLockMask
{
	RLV_LOCK_ADD	= 0x01,
	RLV_LOCK_REMOVE	= 0x02,
	RLV_LOCK_ANY	= RLV_LOCK_ADD | RLV_LOCK_REMOVE
};
enum ERlvWearMask
{
	RLV_WEAR_LOCKED	 = 0x00,
	RLV_WEAR_ADD	 = 0x01,
	RLV_WEAR_REPLACE = 0x02,
	RLV_WEAR		 = 0x03
};
enum ERlvAttachGroupType
{
	RLV_ATTACHGROUP_HEAD = 0,
	RLV_ATTACHGROUP_TORSO,
	RLV_ATTACHGROUP_ARMS,
	RLV_ATTACHGROUP_LEGS,
	RLV_ATTACHGROUP_HUD,
	RLV_ATTACHGROUP_COUNT,
	RLV_ATTACHGROUP_INVALID
};
#define RLV_SETTING_MAIN				"RestrainedLove"
#define RLV_SETTING_DEBUG				"RestrainedLoveDebug"
#define RLV_SETTING_CANOOC				"RestrainedLoveCanOOC"
#define RLV_SETTING_FORBIDGIVETORLV		"RestrainedLoveForbidGiveToRLV"
#define RLV_SETTING_NOSETENV			"RestrainedLoveNoSetEnv"
#define RLV_SETTING_SHOWELLIPSIS		"RestrainedLoveShowEllipsis"
#define RLV_SETTING_WEARADDPREFIX       "RestrainedLoveStackWhenFolderBeginsWith"
#define RLV_SETTING_WEARREPLACEPREFIX   "RestrainedLoveReplaceWhenFolderBeginsWith"
#define RLV_SETTING_DEBUGHIDEUNSETDUP   "RLVaDebugHideUnsetDuplicate"
#define RLV_SETTING_ENABLECOMPOSITES	"RLVaEnableCompositeFolders"
#define RLV_SETTING_ENABLELEGACYNAMING	"RLVaEnableLegacyNaming"
#define RLV_SETTING_ENABLESHAREDWEAR	"RLVaEnableSharedWear"
#define RLV_SETTING_HIDELOCKEDLAYER		"RLVaHideLockedLayers"
#define RLV_SETTING_HIDELOCKEDATTACH	"RLVaHideLockedAttachments"
#define RLV_SETTING_HIDELOCKEDINVENTORY	"RLVaHideLockedInventory"
#define RLV_SETTING_LOGINLASTLOCATION	"RLVaLoginLastLocation"
#define RLV_SETTING_SHAREDINVAUTORENAME	"RLVaSharedInvAutoRename"
#define RLV_SETTING_SHOWASSERTIONFAIL	"RLVaShowAssertionFailures"
#define RLV_SETTING_SHOWNAMETAGS		"RLVaShowNameTags"
#define RLV_SETTING_TOPLEVELMENU		"RLVaTopLevelMenu"
#define RLV_SETTING_WEARREPLACEUNLOCKED	"RLVaWearReplaceUnlocked"
#define RLV_SETTING_FIRSTUSE_PREFIX		"FirstRLV"
#define RLV_SETTING_FIRSTUSE_GIVETORLV	RLV_SETTING_FIRSTUSE_PREFIX"GiveToRLV"
#define RLV_STRING_HIDDEN					"hidden_generic"
#define RLV_STRING_HIDDEN_PARCEL			"hidden_parcel"
#define RLV_STRING_HIDDEN_REGION			"hidden_region"
#define RLV_STRING_BLOCKED_GENERIC			"blocked_generic"
#define RLV_STRING_BLOCKED_PERMATTACH		"blocked_permattach"
#define RLV_STRING_BLOCKED_PERMTELEPORT		"blocked_permteleport"
#define RLV_STRING_BLOCKED_RECVIM			"blocked_recvim"
#define RLV_STRING_BLOCKED_RECVIM_REMOTE	"blocked_recvim_remote"
#define RLV_STRING_BLOCKED_SENDIM			"blocked_sendim"
#define RLV_STRING_BLOCKED_STARTCONF		"blocked_startconf"
#define RLV_STRING_BLOCKED_STARTIM			"blocked_startim"
#define RLV_STRING_BLOCKED_TELEPORT			"blocked_teleport"
#define RLV_STRING_BLOCKED_TPLUREREQ_REMOTE	"blocked_tplurerequest_remote"
#define RLV_STRING_BLOCKED_VIEWXXX			"blocked_viewxxx"
#define RLV_STRING_BLOCKED_WIREFRAME		"blocked_wireframe"
#endif
